### ISSUE TITLE
template bug

### ISSUE THREAD

**Issue by wan2land** [corgidisco/preference#1]
this is my yml file.

```yml
foo: <%=process.env.NOTDEFINED_ENV || 10%>
bar: "bar"
``

The results I expected:

```js
{foo: 10, bar: "bar"}
```

but actual:

```js
{foo: undefined}
```
